### ISSUE TITLE
Quickstart notebbok: Run Multi-Agent DDPG System.

### ISSUE THREAD

**Issue by jbakambana** [instadeepai/Mava#290]
I was playing around with the quickstart notebook but having this error on  Run Multi-Agent DDPG System (I tried locally and on colab):

**UnparsedFlagAccessError**: Trying to access flag --lp_termination_notice_secs before flags were parsed.

**Comment by KaleabTessera** [comment]
Hi @jbakambana, thanks for pointing this out. This was related to an issue with an external library that we use for scaling https://github.com/deepmind/launchpad/issues/14 .   

We have a PR out for this fix (https://github.com/instadeepai/Mava/pull/291). I will let you know when to test this again.

**Comment by arnupretorius** [comment]
Hi @jbakambana, the PR for the fix has been merged. The notebook should work again now 😄 

Please let us know if there are still any issues. Thanks again for pointing this out!

**Comment by jbakambana** [comment]
Hi @arnupretorius , thanks for your feedback. The notebook is working now on colab. But the problem remains when I tried with Desktop even though I reinstalled Mava.

**Comment by KaleabTessera** [comment]
@jbakambana Try printing out your version of launchpad like, ``` pip show dm-launchpad-nightly```. 

It should be `0.3.0.dev20210730`. It it isn't, it means the re-install failed for some reason. Please confirm that you have the latest `setup.py` when you re-installed Mava?

**Comment by jbakambana** [comment]
I got this:   Version: 0.3.0.dev20210809.  How do I check for the setup.py file?

 .

**Comment by KaleabTessera** [comment]
@jbakambana If you are on the develop branch, please do a pull from master (`git pull`). That should pull an updated `setup.py` file. Then after that, re-installing Mava should work.

**Comment by jbakambana** [comment]
Thank you @KaleabTessera it's ok now!

**Comment by KaleabTessera** [comment]
My recent PR retroduced this, I am fixing this to work with latest LP.

**Comment by KaleabTessera** [comment]
Looks fixed.
